dateModified: 1555934581
email:
  fromEmail: kylea@page.works
  fromName: Papertrain
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  d1152418-e6c6-429b-8479-09029014c076:
    name: Common
siteGroups:
  d806d78c-227c-48bd-b01a-0a72122e97c9:
    name: Papertrain
sites:
  7bd1e493-3a06-4f03-bd19-0ebd869d1b82:
    baseUrl: $DEFAULT_SITE_URL
    handle: default
    hasUrls: true
    language: en-US
    name: Papertrain
    primary: true
    siteGroup: d806d78c-227c-48bd-b01a-0a72122e97c9
    sortOrder: 1
system:
  edition: solo
  live: true
  name: Papertrain
  schemaVersion: 3.1.27
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: ''
  photoVolumeUid: null
  requireEmailVerification: true
