dateModified: 1572702993
email:
  fromEmail: 'REPLACE ME'
  fromName: 'REPLACE ME'
  transportType: craft\mail\transportadapters\Sendmail
fieldGroups:
  fd9bbfe1-97ad-43c7-b6cd-81d3a9f92a0b:
    name: Generic
plugins:
  eager-beaver:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  image-resizer:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  imager:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  relabel:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  smith:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  splashing-images:
    edition: standard
    enabled: true
    schemaVersion: 1.2.0
    settings:
      destination: '1'
      folder: ''
      pluginLabel: ''
  typedlinkfield:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  seo:
    edition: standard
    enabled: true
    schemaVersion: 3.1.0
    settings:
      sitemapName: sitemap
      sitemapLimit: '1000'
      titleSuffix: null
      title:
        -
          key: '1'
          locked: '0'
          template: '{title}'
        -
          key: '2'
          locked: '1'
          template: ' - REPLACE ME'
      description: 'This needs to be updated before launch.'
      socialImage: ''
      metaTemplate: ''
      robots:
        - noindex
        - nofollow
        - ''
        - ''
        - ''
        - ''
      robotsTxt: "{# Sitemap URL #}\nSitemap: {{ url(seo.sitemapName ~ '.xml') }}\n\n{# Disallows #}\n{% if craft.app.config.env != 'production' %}\n\n{# Disallow access to everything when NOT in production #}\nUser-agent: *\nDisallow: /\n\n{% else %}\n\n{# Disallow access to cpresources/ when live #}\nUser-agent: *\nDisallow: /cpresources/\n\n{% endif %}"
      facebookAppId: ''
      twitterHandle: ''
  preparse-field:
    edition: standard
    enabled: true
    schemaVersion: 1.0.5
sections:
  84857542-340f-495c-ab00-0099b0341efc:
    name: Homepage
    handle: homepage
    type: single
    enableVersioning: true
    siteSettings:
      471b5ebe-f553-47d6-aa58-d02e5076065c:
        enabledByDefault: true
        hasUrls: true
        uriFormat: __home__
        template: homepage/index.twig
    entryTypes:
      773e89db-a0b1-4f68-b1eb-6e75d9cf9a1d:
        name: Homepage
        handle: homepage
        hasTitleField: false
        titleLabel: null
        titleFormat: '{section.name|raw}'
        sortOrder: 1
    propagationMethod: all
siteGroups:
  7c028f52-0d4d-4794-8cfc-35974c34753b:
    name: Default
sites:
  471b5ebe-f553-47d6-aa58-d02e5076065c:
    siteGroup: 7c028f52-0d4d-4794-8cfc-35974c34753b
    name: English
    handle: default
    language: en-US
    hasUrls: true
    baseUrl: $DEFAULT_SITE_URL
    sortOrder: 1
    primary: true
system:
  edition: solo
  name: $SYSTEM_NAME
  live: true
  schemaVersion: 3.3.3
  timeZone: America/New_York
users:
  requireEmailVerification: true
  allowPublicRegistration: false
  defaultGroup: null
  photoVolumeUid: null
  photoSubpath: ''
volumes:
  734530b2-7176-44fe-9ff8-22d23df70ed0:
    name: Images
    handle: images
    type: craft\volumes\Local
    hasUrls: true
    url: '@web/uploads/images'
    settings:
      path: '@webroot/uploads/images'
    sortOrder: 1
